DmytroVolodymyrson/yima

app.vue, composables/api/order.ts, composables/api/product.ts, pages/index.vue, plugins/order.ts
=> YIMA-19-Cart-BE

.gitignore, nuxt.config.ts, package-lock.json, package.json
=> YIMA-33-Icons-Plugin

composables/services/order.ts, formkit.config.ts, server/lib/firebase.ts, server/lib/firestorage.ts
=> YIMA-31-Firestorage

assets/css/tailwind.css, components/TheHeader.vue, components/product/card.vue, components/quantity-box/index.vue, composables/services/order.ts, formkit.config.ts, lang/ru-RU.json, lang/uk-UA.json, package-lock.json, package.json, pages/index.vue, pages/order.vue
=> YIMA-14-Header

components/TheFooter.vue, components/TheHeader.vue, layouts/default.vue
=> YIMA-15-Footer

app.vue, components/TheHeader.vue, pages/order.vue, tailwind.config.ts
=> YIMA-36-Color-palette

composables/services/order.ts
=> YIMA-35-Checkout-page

components/product/card.vue
=> YIMA-16-Products-list

server/api/login.post.ts
=> feat(client, server): added basic admin

server/api/login.post.ts
=> fix(server): fixed admin

components/TheHeader.vue, components/product/card.vue, composables/api/product.ts, composables/services/product.ts, composables/services/search.ts, config/eslintrc.js, middleware/order.ts, pages/index.vue, pages/order.vue, pages/order/contact.vue, plugins/http.ts, server/api/products.get.ts, server/lib/typesense.ts
=> YIMA-44-Sort

Dockerfile, docker-compose.yaml
=> YIMA-47-Add-Docker

components/TheHeader.vue, components/product/Card.vue, components/quantity-box/Index.vue, composables/api/product.ts, package-lock.json, package.json, pages/[slug].vue, plugins/order.ts, server/api/products/[slug].ts, server/utils/getCategories.ts
=> YIMA-32-Product-detail-page

.gitignore, composables/api/order.ts, composables/services/order.ts, server/api/orders/index.post.ts
=> feat(server): added firebase functions for completing order

components/TheSlider.vue, components/admin/product/Attributes.vue, components/product/filters/Index.vue, composables/services/utils.ts, lang/uk-UA.json, pages/[slug].vue, pages/admin/products/index.vue, pages/admin/products/new.vue, pages/index.vue, server/api/admin/products/index.get.ts, server/api/products/filters.get.ts, server/api/products/index.get.ts, server/lib/firestore.ts
=> YIMA-51-Fixes

components/product/Card.vue, components/product/List.vue, lang/uk-UA.json, package-lock.json, package.json, pages/admin/products/index.vue, pages/index.vue, plugins/autoAnimate.ts, server/api/products/index.get.ts
=> YIMA-52-Auto-animate

composables/services/utils.ts, pages/index.vue
=> fix(client): small fixes

components/product/Card.vue, composables/services/product.ts, pages/[slug].vue, server/api/products/[slug].ts
=> YIMA-57-add-min-amount-product-purchase

components/TheFooter.vue
=> YIMA-59-add-telegram-link

components/homepage/chosenProducts.vue
=> YIMA-58-add-free-delivery-block

components/TheHeader.vue, middleware/order.ts, pages/order/contact.vue
=> YIMA-65-add-telephone-mask-to-order

components/product/Card.vue
=> YIMA-63-delete-categories-from-product-cards

assets/css/tailwind.css, components/TheBaseCard.vue, components/TheDarkModeSwitcher.vue, formkit.config.ts, pages/admin.vue, pages/index.vue, tailwind.config.ts
=> YIMA-67-change-primary-color

components/order/AddressAutocomplete.vue, composables/services/order.ts, lang/uk-UA.json, pages/order/contact.vue
=> YIMA-64-add-cities-API

components/product/Card.vue, components/product/List.vue
=> YIMA-78-add-product-quantity-selection-before-adding-to-cart

components/TheHeader.vue
=> YIMA-76-delete-login-button

assets/css/tailwind.css, components/TheButton.vue, components/admin/category/rowItem.vue, pages/admin/attributes/index.vue, pages/admin/products/index.vue, tailwind.config.ts
=> YIMA-83-change-attributes-color-for-dark-theme

components/admin/Menu.vue, composables/api/admin/order.ts, composables/services/admin/order.ts, pages/admin/orders/[id].vue, server/api/orders/[id]/index.put.ts, server/lib/utils.ts
=> YIMA-95-add-delete-product-from-order

composables/services/admin/order.ts, composables/services/utils.ts, package-lock.json, package.json, pages/admin/orders/index.vue, server/api/orders/index.get.ts, server/lib/firestore.ts
=> YIMA-88-add-a-calendar

components/product/Card.vue
=> YIMA-75-add-text-not-in-stock

components/product/Slider.vue
=> YIMA-97-fix-bug-with-slider-and-counter

server/lib/clientCategoryCache.ts
Potential multi-thread behaviour fix
=> Yima 101 categories load optimization

lang/en-US.json, lang/uk-UA.json, pages/admin/products/index.vue, server/api/admin/products/index.get.ts, server/api/products/index.get.ts
Modify admin products page to include paginated search
=> Implement product search in admin products page

components/product/Card.vue, components/product/List.vue
Fix wrong product property being consumed by api
=> Fix modal not being displayed

pages/[slug].vue, pages/index.vue
Add autoscroll to top when applying filters, fix white text on white background in tag fields.
=> UI/UX Improvements

lang/en-US.json, lang/uk-UA.json
=> Fix Product Type Label

components/product/Card.vue, lang/en-US.json, lang/uk-UA.json
=> Update product card 'details' button - rename to 'choose type'
